apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-basic
  labels:
    io.kompose.service: ubuntu-basic
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ubuntu-basic
  template:
    metadata:
      labels:
        io.kompose.service: ubuntu-basic
    spec:
      containers:
        - name: ubuntu-basic
          image: avarf/ubuntu-basic
          args:
          - /bin/sh
          - -c
          - tail -f /dev/null
          resources:
            requests:
              cpu: 0.1
              memory: 50Mi
            limits:
              cpu: 0.2
              memory: 250Mi
      restartPolicy: Always
status: {}
